version: '2'
services:
    storedemo-app:
        image: storedemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://storedemo-postgresql:5432/storeDemo
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    storedemo-postgresql:
        extends:
            file: postgresql.yml
            service: storedemo-postgresql
